name: Validate Gradle Wrapper

on:
  workflow_call:

jobs:

  validateGradle:
    name: Validate Gradle Wrapper
    runs-on: ubuntu-latest

    steps:

      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
