name: Publish Snapshot

on:
  workflow_call:

jobs:
  publishSnapshot:
    name: Publish
    runs-on: ubuntu-latest
    env:
      JRELEASER_NEXUS2_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
      JRELEASER_NEXUS2_PASSWORD: ${{ secrets.MAVENCENTRAL_PASSWORD }}
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4.7.0
        with:
          distribution: zulu
          java-version: 17
      - name: Verify Configuration
        run: ./gradlew jreleaserConfig -PprojectVersionSuffix="SNAPSHOT" --stacktrace
      - name: Stage Artifacts
        run: ./gradlew clean publish -PprojectVersionSuffix="SNAPSHOT" --stacktrace
      - name: Publish Snapshots to Maven Central
        run: ./gradlew jreleaserFullRelease -PprojectVersionSuffix="SNAPSHOT" --stacktrace
